### ISSUE TITLE
Archive this repo and redirect to the official Mac app?

### ISSUE THREAD

**Issue by robbiet480** [moallemi/home-assistant-mac#6]
Hi @moallemi!

Was wondering if you’d be willing to archive this repository and add a big note in the README that we now have an official Mac app at https://github.com/home-assistant/iOS/releases ? We’ve recently had some issues think this repo is the official HA Mac app due to the name.

Thanks for considering!

**Comment by moallemi** [comment]
Hi @robbiet480 
Done
